name: Deploy
on:
  push:
    branches: [ master ]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing ssh connection
        uses: appleboy/ssh-action@master
        with: 
          host: soulforger.net
          username: simeon
          password: ${{ secrets.SUDO_PW }}
          key: ${{ secrets.SSH_KEY }}
          port: 25540
          script: |
            cd dsa.soulforger.net/api/
            git pull origin master
            docker stop API
            docker rm API
            docker rmi soulforger-api 
            docker build -t soulforger-api .
            docker run --name API --link mongoDB:mongo -p 8000:8000 --user user -d soulforger-api
            docker ps